### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by zenshixd** [zenshixd/zapts#1]
https://tc39.es/ecma262/

Lexer:
- [x] all (?) tokens work
- [x] remove .value from Token field - add separate function for reading literals
- [x] fix lexer performance - using StringHashMap is slower than keeping pointer to str in Token struct
- [x] split ">>" as token - interferes with generics e.g. `T<G<number>>`

AST:
- [x] should I use arena for AST parsing?? temp results are now not cleaned up and i just learned ArrayList doesnt grow linearly
- [x] rewinding cur_token - doesnt remove already added nodes (look parseMethod())
